name: Tests
on: [push, pull_request]
jobs:
  MesonTests:
    name: Meson Linux Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: sudo apt-get install ninja-build gcovr libcfitsio-dev python-is-python3 libboost-python-dev python3-numpy && sudo pip3 install meson
      - name: Checkout photospline
        uses: actions/checkout@v2
        with:
          repository: icecube/photospline
          ref: v2.0.7
          path: photospline
      - name: Build photospline
        run: |
          cmake .
          make
          sudo make install
        working-directory: photospline
      - name: Checkout nuflux
        uses: actions/checkout@v2
        with:
          path: nuflux
      - name: Build nuflux
        run: |
          meson nuflux -D b_coverage=true
          ninja
          sudo ninja install
      - name: Run tests
        run: ninja test
        env:
          LD_LIBRARY_PATH: /usr/local/lib/x86_64-linux-gnu:/usr/local/lib/
          PYTHONPATH: /usr/local/lib/python3.8/site-packages
      - name: Generate Coverage repository
        run: ninja coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          verbose: true
  SetupToolsLinuxTests:
    name: SetupTools Linux Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: sudo apt-get install libcfitsio-dev python-is-python3 libboost-python-dev python3-numpy
      - name: Checkout photospline
        uses: actions/checkout@v2
        with:
          repository: icecube/photospline
          ref: v2.0.7
          path: photospline
      - name: Build photospline
        run: cmake . && make && sudo make install
        working-directory: photospline
      - name: Checkout nuflux
        uses: actions/checkout@v2
      - name: Build nuflux
        run: sudo pip install .
      - name: Run tests
        run: ./tests/test_fluxes.py
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
  SetupToolsMacOSTests:
    name: SetupTools MacOS Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install dependencies
        run: brew tap icecube/homebrew-icecube && brew install photospline boost-python3 numpy
      - name: Checkout nuflux
        uses: actions/checkout@v2
      - name: Build nuflux
        run: pip3 install . --use-feature=in-tree-build
      - name: Run tests
        run: ./tests/test_fluxes.py
